spring.application.name=biblioteca

# Conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Biblioteca?createDatabaseIfNotExist=true
spring.datasource.username=in5am
spring.datasource.password=_odmon5Am
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Inicialización de datos (data.sql)
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# HikariCP (pool de conexiones)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# JWT
jwt.secret=Zm9vYmFyLXN1cGVyLXNlY2V0by1jaGF2ZS1qd3QtdGltby13ZWRzZXQtZGVyYTIzMjM=
jwt.expiracion-ms=86400000
